language: c

compiler:
    - gcc

notifications:
    email:
        on_success: never
        on_failure: never

script:
    # Clase 1
    - cd ./clase1
    - gcc -std=c99 helloworld.c -o helloworld.out
    # Clase 2
        # Directorio tiposArraysCadenas
    - cd ../clase2/tiposArraysCadenas
    - gcc -std=c99 printSize.c -o printSize.out
    - gcc -std=c99 matrices.c -o matrices.out
    - gcc -std=c99 cadenas.c -o cadenas.out
    - gcc -std=c99 arrays.c -o arrays.out
        # Directorio punteros
    - cd ../punteros
    - gcc -std=c99 matrices.c -o matrices.out
    - gcc -std=c99 sintaxis.c -o sintaxis.out
    - gcc -std=c99 magic.c -o magic.out
    - gcc -std=c99 arraysPunteros.c -o arraysPunteros.out
    # Clase 3
        # Directorio estructurasEnumerados
    - cd ../../clase3/estructurasEnumerados
    - gcc -std=c99 car.c -o car.out
    - gcc -std=c99 person.c -o person.out
        # Directorio macrosUnionesCampos
    - cd ../macrosUnionesCampos
    - gcc -std=c99 union.c -o union.out
    - gcc -std=c99 mayusculas.c -o mayusculas.out
    - gcc -std=c99 chorradas.c -o chorradas.out
        # Directorio cabecerasFunciones
    - cd ../cabecerasFunciones
    - gcc -std=c99 swap.c -o swap.out
